#!/usr/bin/env bash
# Rebuild database-import-all-in-one.sql after editing database-schema.sql or database-dump.sql
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/database-import-all-in-one.sql"
{
  echo "-- ============================================================================="
  echo "-- SINGLE-FILE IMPORT: empty database only (drops/creates tables, then loads data)."
  echo "-- Same as: database-schema.sql then database-dump.sql"
  echo "-- Regenerated by: scripts/build-database-import-all-in-one.sh"
  echo "-- ============================================================================="
  echo ""
  cat "$ROOT/database-schema.sql"
  echo ""
  cat "$ROOT/database-dump.sql"
} > "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
